[build]
  base = "frontend/app"       # folder with package.json
  publish = "dist"            # relative to base
  command = "npm install && npm run build"

[dev]
  command = "npm run serve"
  port = 5173
